lossy = [(738, 'Рок, Панк, Альтернатива (lossy)'), 
         (1703, 'Classic Rock & Hard Rock (lossy)'),
         (1705, 'Progressive & Art-Rock (lossy)'),
         (1749, 'Gothic Rock & Dark Folk (lossy)'),
         (1799, 'Сборники зарубежного рока (lossy)'),
         (1743, 'Indie, Post-Rock & Post-Punk (lossy)'),
         (1709, 'Pop-Rock & Soft Rock (lossy)'),
         (740, 'Металл (lossy)'),
         (1737, 'Alternative & Nu-metal (lossy)'),
         (1713, "Rockabilly, Psychobilly, Rock'n'Roll (lossy)"),
         (2231, 'Сборники (lossy)'),
         (1715, 'Восточноазиатский рок (lossy)'),
         (1731, 'Grind, Brutal Death (lossy)'),
         (798, 'Folk, Pagan, Viking (lossy)'),
         (1727, 'Heavy, Power, Progressive (lossy)'),
         (1729, 'Thrash, Speed (lossy)'),
         (1725, 'Gothic Metal (lossy)'),
         (1739, 'Punk (lossy)'),
         (1711, 'Instrumental Guitar Rock (lossy)'),
         (952, 'Рок на языках народов xUSSR (lossy)'),
         (1778, 'Black (lossy)'),
         (1780, 'Death, Doom (lossy)'),
         (2330, 'AOR (Melodic Hard Rock, Arena rock) (lossy)'),
         (1747, 'Emocore, Post-hardcore, Metalcore (lossy)'),
         (1745, 'Industrial & Post-industrial (lossy)'),
         (1816, 'Sludge, Stoner, Post-Metal (lossy)'),
         (1797, 'Avant-garde, Experimental Metal (lossy)'),
         (1707, 'Folk-Rock (lossy)'),
         (1741, 'Hardcore (lossy)'),
         (2174, 'Avant-garde, Experimental Rock (lossy)'),
         (1858, 'House (lossy)'),
         (1819, 'Trance (lossy)'),
         (1822, 'Goa Trance, Psy-Trance (lossy)'),
         (1862, 'Chillout, Lounge, Downtempo (lossy)'),
         (1833, 'Drum & Bass, Jungle (lossy)'),
         (1946, 'Nu Jazz, Acid Jazz, Future Jazz (lossy)'),
         (1837, 'Breakbeat (lossy)'),
         (1824, 'Trance (Radioshows, Podcasts, Live Sets, Mixes) (lossy)'),
         (1865, 'Traditional Electronic, Ambient (lossy)'),
         (1830, 'Hardcore, Hardstyle, Jumpstyle (lossy)'),
         (1648, 'Label packs, Scene packs (lossy)'),
         (1826, 'Techno (lossy)'),
         (1881, 'Synthpop, New Wave (lossy)'),
         (1860, 'House (Singles, EPs) (lossy)'),
         (1944, 'Trip Hop, Abstract Hip-Hop (lossy)'),
         (1878, 'Industrial, Noise (lossy)'),
         (406, 'Darkwave, Neoclassical, Ethereal, Dungeon Synth (lossy)'),
         (460, 'Goa Trance, Psy-Trance, PsyChill, Ambient, Dub (Live Sets, Mixes) (lossy)'),
         (1828, 'Techno (Singles, EPs) (lossy)'),
         (1895, 'PsyChill, Ambient, Dub (lossy)'),
         (454, 'Dubstep (lossy)'),
         (1841, 'IDM (lossy)'),
         (1875, 'EBM, Dark Electro, Aggrotech (lossy)'),
         (1847, 'Trance (Singles, EPs) (lossy)'),
         (2229, 'IDM Discography & Collections (lossy)'),
         (1867, 'Modern Classical, Electroacoustic (lossy)'),
         (1805, 'Electro, Electro-Freestyle, Nu Electro (lossy)'),
         (1873, 'Experimental (lossy)'),
         (2287, 'Зарубежный джаз (lossy)'),
         (2288, 'Зарубежный блюз (lossy)'),
         (2295, 'Отечественный джаз (lossy)'),
         (2298, 'Отечественный блюз (lossy)'),
         (1361, 'Отечественная поп-музыка (сборники) (lossy)'),
         (424, 'Отечественная поп-музыка (lossy)'),
         (1635, 'Советская эстрада, Ретро (lossy)'),
         (1362, 'Зарубежная поп-музыка (сборники) (lossy)'),
         (428, 'Зарубежная поп-музыка (lossy)'),
         (2503, 'Eurodance, Euro-House, Technopop (lossy)'),
         (2501, 'Disco, Italo-Disco, Euro-Disco, Hi-NRG (lossy)'),
         (2505, 'Disco, Italo-Disco, Euro-Disco, Hi-NRG (сборники) (lossy)'),
         (2504, 'Eurodance, Euro-House, Technopop (сборники) (lossy)'),
         (1219, 'Зарубежный шансон (lossy)'),
         (1331, 'Восточноазиатская поп-музыка (lossy)'),
         (965, 'Неофициальные и внежанровые сборники (lossy)'),
         (1396, 'Православные песнопения (lossy)'),
         (463, 'Отечественная музыка других жанров (lossy)'),
         (1225, 'Авторская песня (lossy)'),
         (469, 'Саундтреки к отечественным фильмам (lossy)'),
         (441, 'Отечественный Рэп, Хип-Хоп (lossy)'),
         (1223, 'Военная песня (lossy)'),
         (796, 'Неофициальные саундтреки к фильмам и сериалам (lossy)'),
         (1334, 'Сборники отечественного шансона (lossy)'),
         (2311, 'Камерная и сольная инструментальная музыка (lossy)'),
         (1134, 'Фламенко и акустическая гитара (lossy)'),
         (1126, 'NewAge & Meditative (lossy)'),
         (466, 'Зарубежная музыка других жанров (lossy)'),
         (1284, 'Этническая музыка Северной и Южной Америки (lossy)'),
         (785, 'Саундтреки к зарубежным фильмам (lossy)'),
         (855, 'Звуки природы'),
         (1172, "Зарубежный R'n'B (lossy)"),
         (1136, 'Country, Bluegrass (lossy)'),
         (1130, 'Восточноевропейский фолк (lossy)'),
         (2310, 'Оркестровая музыка (lossy)'),
         (2331, 'Неофициальные саундтреки к играм (lossy)'),
         (1132, 'Западноевропейский фолк (lossy)'),
         (2309, 'Вокальная и хоровая музыка (lossy)'),
         (783, 'Саундтреки к играм (lossy)'),
         (1173, "Отечественный R'n'B (lossy)"),
         (1769, 'Ska-Punk, Ska-Core (lossy)'),
         (1128, 'Этническая музыка Сибири, Средней и Восточной Азии (lossy)'),
         (1221, 'Отечественный шансон (lossy)'),
         (446, 'Зарубежный Рэп, Хип-Хоп (lossy)'),
         (1283, 'Этническая музыка Африки и Ближнего Востока (lossy)'),
         (436, 'Полные собрания сочинений и многодисковые издания (lossy)'),
         (1765, 'Reggae (lossy)'),
         (1856, 'Этническая музыка Индии (lossy)'),
         (1770, 'Dancehall, Raggamuffin (lossy)'),
         (1767, '3rd Wave Ska (lossy)'),
         (1766, 'Punky-Reggae, Rocksteady-Punk, Ska Revival (lossy)'),
         (1771, 'Dub (lossy)')]
lossles = [(1726, 'Heavy, Power, Progressive (lossless)'),
         (1742, 'Indie, Post-Rock & Post-Punk (lossless)'),
         (1719, 'Black (lossless)'),
         (1736, 'Alternative & Nu-metal (lossless)'),
         (1708, 'Pop-Rock & Soft Rock (lossless)'),
         (1738, 'Punk (lossless)'),
         (1702, 'Classic Rock & Hard Rock (lossless)'),
         (737, 'Рок, Панк, Альтернатива (lossless)'),
         (1706, 'Folk-Rock (lossless)'),
         (739, 'Металл (lossless)'),
         (1704, 'Progressive & Art-Rock (lossless)'),
         (1779, 'Death, Doom (lossless)'),
         (1710, 'Instrumental Guitar Rock (lossless)'),
         (1714, 'Восточноазиатский рок (lossless)'),
         (2329, 'AOR (Melodic Hard Rock, Arena rock) (lossless)'),
         (1748, 'Gothic Rock & Dark Folk (lossless)'),
         (1796, 'Avant-garde, Experimental Metal (lossless)'),
         (1712, "Rockabilly, Psychobilly, Rock'n'Roll (lossless)"),
         (1724, 'Gothic Metal (lossless)'),
         (1720, 'Folk, Pagan, Viking (lossless)'),
         (1744, 'Industrial & Post-industrial (lossless)'),
         (1740, 'Hardcore (lossless)'),
         (951, 'Рок на языках народов xUSSR (lossless)'),
         (2230, 'Сборники (lossless)'),
         (1728, 'Thrash, Speed (lossless)'),
         (731, 'Сборники зарубежного рока (lossless)'),
         (1815, 'Sludge, Stoner, Post-Metal (lossless)'),
         (1746, 'Emocore, Post-hardcore, Metalcore (lossless)'),
         (1730, 'Grind, Brutal Death (lossless)'),
         (2175, 'Avant-garde, Experimental Rock (lossless)'),
         (1861, 'Chillout, Lounge, Downtempo (lossless)'),
         (1894, 'PsyChill, Ambient, Dub (lossless)'),
         (1844, 'Goa Trance, Psy-Trance (lossless)'),
         (1832, 'Drum & Bass, Jungle (lossless)'),
         (840, 'House (Проморелизы, сборники)'),
         (1880, 'Synthpop, New Wave (lossless)'),
         (1945, 'Trip Hop, Abstract Hip-Hop (lossless)'),
         (1834, 'Drum & Bass, Jungle (Radioshows, Podcasts, Livesets, Mixes)'),
         (1827, 'Techno (Radioshows, Podcasts, Livesets, Mixes)'),
         (1840, 'IDM (lossless)'),
         (1836, 'Breakbeat (lossless)'),
         (1864, 'Traditional Electronic, Ambient (lossless)'),
         (1859, 'House (Radioshow, Podcast, Liveset, Mixes)'),
         (1818, 'Trance (lossless)'),
         (1871, 'Modern Classical, Electroacoustic (lossless)'),
         (1947, 'Nu Jazz, Acid Jazz, Future Jazz (lossless)'),
         (1857, 'House (lossless)'),
         (1877, 'Industrial, Noise (lossless)'),
         (1838, 'Breakbeat, Dubstep (Radioshows, Podcasts, Livesets, Mixes)'),
         (1829, 'Hardcore, Hardstyle, Jumpstyle (lossless)'),
         (1866, 'Darkwave, Neoclassical, Ethereal, Dungeon Synth (lossless)'),
         (1868, 'EBM, Dark Electro, Aggrotech (lossless)'),
         (1825, 'Techno (lossless)'),
         (1907, '8-bit, Chiptune (lossy & lossless)'),
         (1869, 'Experimental (lossless)'),
         (1839, 'Dubstep (lossless)'),
         (797, 'Electro, Electro-Freestyle, Nu Electro (lossless)'),
         (1831, 'Hardcore, Hardstyle, Jumpstyle (vinyl, web)'),
         (1842, 'Label Packs (lossless)'),
         (1808, 'Drum & Bass, Jungle, Breakbeat, Dubstep, IDM, Electro'),
         (2297, 'Отечественный джаз (lossless)'),
         (2277, 'Early Jazz, Swing, Gypsy (lossless)'),
         (2279, 'Mainstream Jazz, Cool (lossless)'),
         (2281, 'World Fusion, Ethnic Jazz (lossless)'),
         (2284, 'Smooth, Jazz-Pop (lossless)'),
         (2296, 'Отечественный блюз (lossless)'),
         (2278, 'Bop (lossless)'),
         (2285, 'Vocal Jazz (lossless)'),
         (2283, 'Funk, Soul, R&B (lossless)'),
         (2353, 'Modern Creative, Third Stream (lossless)'),
         (2292, 'Blues-rock (lossless)'),
         (2280, 'Jazz Fusion (lossless)'),
         (2293, 'Blues (Texas, Chicago, Modern and Others) (lossless)'),
         (2282, 'Avant-Garde Jazz, Free Improvisation (lossless)'),
         (2289, 'Зарубежный блюз (сборники; Tribute VA) (lossless)'),
         (2286, 'Сборники зарубежного джаза (lossless)'),
         (2290, 'Roots, Pre-War Blues, Early R&B, Gospel (lossless)'),
         (429, 'Зарубежная поп-музыка (lossless)'),
         (425, 'Отечественная поп-музыка (lossless)'),
         (1634, 'Советская эстрада, Ретро (lossless)'),
         (2500, 'Disco, Italo-Disco, Euro-Disco, Hi-NRG (lossless)'),
         (1452, 'Зарубежный шансон (lossless)'),
         (2502, 'Eurodance, Euro-House, Technopop (lossless)'),
         (1330, 'Восточноазиатская поп-музыка (lossless)'),
         (239, 'Отечественная поп-музыка (оцифровки)'),
         (450, 'Инструментальная поп-музыка (оцифровки)'),
         (1227, 'Видео (Шансон и Авторская песня)'),
         (465, 'Зарубежная музыка других жанров (lossless)'),
         (2084, 'Klezmer и Еврейский фольклор (lossy и lossless)'),
         (1282, 'Этническая музыка Кавказа и Закавказья (lossy и lossless)'),
         (793, 'Сольная инструментальная музыка (lossless)'),
         (794, 'Опера (lossless)'),
         (1351, 'Сборники песен для детей (lossy и lossless)'),
         (880, 'Мюзикл (lossy и lossless)'),
         (2233, 'Reggae, Ska, Dub (компиляции) (lossy и lossless)'),
         (969, 'Классика в современной обработке, Classical Crossover (lossy и lossless)'),
         (855, 'Звуки природы'),
         (1129, 'Этническая музыка Сибири, Средней и Восточной Азии (lossless)'),
         (944, 'Академическая музыка (Ноты и Media CD)'),
         (980, 'Другие направления (Ноты, табулатуры)'),
         (2074, 'Музыкальная литература и Теория'),
         (557, 'Оркестровая музыка (lossless)'),
         (556, 'Вокальная музыка (lossless)'),
         (1216, 'Военная песня (lossless)'),
         (946, 'Самоучители и Школы'),
         (782, 'Караоке (аудио)'),
         (2308, 'Концерт для инструмента с оркестром (lossless)'),
         (1224, 'Авторская песня (lossless)'),
         (1127, 'NewAge & Meditative (lossless)'),
         (558, 'Камерная инструментальная музыка (lossless)'),
         (1220, 'Отечественный шансон (lossless)'),
         (1285, 'Этническая музыка Северной и Южной Америки (lossless)'),
         (691, 'Саундтреки к отечественным фильмам (lossless)'),
         (1772, 'Отечественный реггей, даб (lossy и lossless)'),
         (1135, 'Фламенко и акустическая гитара (lossless)'),
         (560, 'Полные собрания сочинений и многодисковые издания (lossless)'),
         (464, 'Отечественная музыка других жанров (lossless)'),
         (1131, 'Восточноевропейский фолк (lossless)'),
         (786, 'Саундтреки к зарубежным фильмам (lossless)'),
         (1774, 'Ska, Ska-Punk, Ska-Jazz (lossless)'),
         (2430, 'Этническая музыка Индии (lossless)'),
         (2307, 'Хоровая музыка (lossless)'),
         (468, 'Минусовки (lossy и lossless)'),
         (1768, 'Reggae, Dancehall, Dub (lossless)'),
         (1133, 'Западноевропейский фолк (lossless)'),
         (1764, 'Rocksteady, Early Reggae, Ska-Jazz, Trad.Ska (lossy и lossless)'),
         (1395, 'Православные песнопения (lossless)'),
         (1773, 'Отечественная ска-музыка (lossy и lossless)'),
         (2085, 'Этническая музыка Африки и Ближнего Востока (lossless)'),
         (1665, "Зарубежный R'n'B (lossless)"),
         (784, 'Саундтреки к играм (lossless)'),
         (909, 'Зарубежный Рэп, Хип-Хоп (lossless)'),
         (1226, 'Менестрели и ролевики (lossy и lossless)'),
         (1137, 'Country, Bluegrass (lossless)'),
         (2431, 'Аранжировки музыки из игр (lossy и lossless)'),
         (2018, 'Музыка для бальных танцев (lossy и lossless)'),
         (1138, 'Этническая музыка Австралии, Тихого и Индийского океанов (lossy и lossless)'),
         (1486, "Отечественный Рэп, Хип-Хоп, R'n'B (lossless)"),
         (977, 'Песенники (Songbooks)'),
         (2349, 'Музыкальные журналы'),
         (506, 'Фольклор, народная и этническая музыка (оцифровки)')]
